version: '2.1'

services:

    mysql:
        image: percona:latest
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test_qa
            MYSQL_PASSWORD: qa_test
            MYSQL_DATABASE: test


    vk_api:
        build: .
        ports:
            - "5000:5000"

    myapp:
        image: myapp:latest
        ports:
            - "8080:8080"
        depends_on:
            vk_api:
                condition: service_started
        volumes:
            - ./config:/config
        entrypoint: "/app/myapp --config=/config/conf"
        links:
            - mysql
            - vk_api
        restart: always

networks:
  default:
    external:
      name: test_network